package com.dollop.hbh_service_engineer.basic.UtilityTools


interface Constants {
    companion object {
        const val TEXT_PLAIN_TYPE = "text/plain"
        const val CONTENT_IMAGE = "image/jpeg"
        const val CONTENT_ALL_IMAGE = "image/*"
        const val IMAGE_JPEG = ".jpeg"
        const val PDF = ".pdf"
        const val pdf = "pdf"
        const val videoUrl = "videoUrl"
        const val urlType = "urlType"
        const val video = "Video"
        const val CONTENT_ALL_DOC = "application/pdf"
        const val Unauthorized = 401
        const val currency = "₹"
        const val doc = "doc"
        const val docx = "docx"
        const val jpg = "jpg"
        const val png = "png"
        const val PNG = ".png"
        const val jpeg = "jpeg"
        const val heic = "heic"
        const val studentLoginHistoryId = "studentLoginHistoryId"

        //Environment
        const val Debug = "Debug"
        const val Live = "Live"
        const val Test = "Test"

        //Bundle Constant and Keys
        const val From = "From"

        //Parameters
        const val Authorization = "Authorization"

        //Firebase
        const val Notification = "Notification"

        //Action Firebase
        const val action = "action"
        const val payload = "payload"
        const val data = "data"
        const val message = "message"
        const val title = "title"

        // Language
        const val blank = ""
        const val Default_Country_Code = "+91"
        const val Default_Country_Region = "IN"
        const val english = "en"
        const val forgotPassword = "forgot-password"
        const val Yes = "Yes"
        const val Android = "Android"
        const val studentMobileNo = "studentMobileNo"
        const val countryCode = "countryCode"
        const val password = "password"
        const val otp = "otp"
        const val fcmId = "fcmId"
        const val deviceType = "deviceType"
        const val loginDeviceType = "loginDeviceType"
        const val device_type = "device_type"
        const val studentEmail = "studentEmail"
        const val loginType = "loginType"
        const val studentName = "studentName"
        const val name = "name"
        const val email = "email"
        const val Email = "Email"
        const val mobile = "mobileNo"
        const val android = "android"
        const val studentId = "studentId"

        //String device_type = "device_type";
        const val Take_Photo = "Take Photo"
        const val Choose_From_Gallery = "Choose from Gallery"
        const val Exit = "Exit"
        const val Need_Permissions = "Need Permissions"
        const val GOTO_SETTINGS = "GOTO SETTINGS"
        const val Package = "package"
        const val Cancel = "Cancel"
        const val Data = "data"
        const val Google = "Google"
        const val Massage = "massage"
        const val Activity = "Activity"
        const val profilePic = "profilePic"
        const val DefaultCountryUuId = "d428a700-0bf7-11ed-9481-000c291151eb"
        const val type = "type"
        const val page_name = "page_name"
        const val updateProfile = "updateProfile"
        const val On = "On"
        const val all = "all"
        const val warning = "warning"
        const val success = "success"
        const val error = "error"
        const val terms = "terms"
        const val privacyPolicy = "privacyPolicy"
        const val token = "token"
        const val Complain_Id = "complaintId"
        const val Status = "Status"
        const val callStatus = "callStatus"
        const val Password_Changed_Successfully = "Password Changed Successfully"
        const val Please_turn_on_location = "Please turn on location"
        const val Closed = "Closed"
        const val Check_In_Comments = "Check In Comments"
        const val Check_Out_Comments = "Check Out Comments"
        const val In_Progress = "In Progress"
        const val Please_Enter_Signature = "Please enter a Signature in the Signature pad"
        const val Open = "Open"
        const val Attachement = "Attachement"
        const val attachement = "attachement"
        const val signature = "signature"
        const val Check_In = "Check In"
        const val Check_Out = "Check Out"
        const val checkOut = "checkOut"
        const val checkIn = "checkIn"
        const val Success = "Success"
        const val StartJob = "startJob"
        const val Start_Job = "Start Job"
        const val Today_Assigned = "Today Assigned"
        const val Mobile = "Mobile"
        const val Pending = "Pending"
        const val Inprogress = "Inprogress"
        const val Redirect_Status = "Redirect_Status"

    }
}
